### ISSUE TITLE
Problem: I can't start my app, I get an error about the length of a path

### ISSUE THREAD

**Issue by mnezmah** [Codaisseur/fullstack-labs#10]
Summary: 
I can not connect start my app

Steps to reproduce
1. Ran `node index.js`

Expected result: 
Node should run `index.js` and return a message 'listening on port 4200'

Actual result:
Node threw a TypeError.

Logs and Errors:
```
/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/node_modules/path-to-regexp/index.js:63
  path = ('^' + path + (strict ? '' : path[path.length - 1] === '/' ? '?' : '/?'))
                                                ^

TypeError: Cannot read property 'length' of undefined
    at pathtoRegexp (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/node_modules/path-to-regexp/index.js:63:49)
    at new Layer (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/node_modules/express/lib/router/layer.js:45:17)
    at Function.route (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/node_modules/express/lib/router/index.js:494:15)
    at Function.proto.(anonymous function) [as get] (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/node_modules/express/lib/router/index.js:509:22)
    at Object.<anonymous> (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/Advertisments/router.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/index.js:2:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by mnezmah** [comment]
The problem was a `router.get` call that was not passed a path or a route handler. On line 6 of my `router.js` file, I just had the code `router.get()`.

A router registration must be passed a path string and a route handler function, like `router.get("/path", (request, response) => response.send(data))`.

I figured this out by finding the first line of the error stack trace that referenced my code, which was;
`<anonymous> (/home/mario/web-develompent-c/codaisseur/week-6/buy-and-sell/server/Advertisments/router.js:6:8)`

The end of that line where it says `router.js:6:8`, told me that it was in my `router.js` on line 6.
