### ISSUE TITLE
Problem: Express expects a middleware function

### ISSUE THREAD

**Issue by ajvanliere** [Codaisseur/fullstack-labs#2]
Summary
When I start the server, I get an error about express needing a middleware function.

Steps to reproduce:
1. Register routes with express.
1. Start the server

Expected result:
The server should start and confirm that express is listening on the correct port.

Actual result:
Express throws a TypeError

Relevant logs and errors:
```
/home/ajvanliere/codaisseur/week6/myEbay/server/node_modules/express/lib/application.js:210
    throw new TypeError('app.use() requires a middleware function')
    ^

TypeError: app.use() requires a middleware function
    at Function.use (/home/ajvanliere/codaisseur/week6/myEbay/server/node_modules/express/lib/application.js:210:11)
    at Object.<anonymous> (/home/ajvanliere/codaisseur/week6/myEbay/server/index.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by davidystephenson** [comment]
This issue was caused by the router not being exported in the file it was defined. Express attempted to integrate the router with `app.use`, but was not able to import the function, resulting in the error. The fix was to add `module.exports = router` to the end of the corresponding `routes` file.
