### ISSUE TITLE
Problem: Sequelize validation error with foreign keys

### ISSUE THREAD

**Issue by olrafa** [Codaisseur/fullstack-labs#3]
Summary:
When I post a new entity defined in a Sequelize model that has a `belongsTo` relation, Sequelize throws an error if I don't define the foreign key myself. Shouldn't sequelize do that for me?

Steps to reproduce:
1. Defined a Sequelize model.
1. Created a POST route handler to add rows to the associated table.
1. Sent a POST request to the route using httpie that defined all the other properties, just not the foreign key.

Expected result;
Sequelize adds a new row to the table with the correct foreign key, created a new related entity if it does not exist.

Actual result:
Sequelize throws a ValidationError.

Relevant logs:
```
SequelizeValidationError: notNull Violation: items.pictureUrl cannot be null,<br>notNull Violation: items.userId cannot be null<br> &nbsp; &nbsp;at /home/rafael/codaisseur/week6/wednesday/backend/node_modules/sequelize/lib/instance-validator.js:74:15<br> &nbsp; &nbsp;at tryCatcher (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/util.js:16:23)<br> &nbsp; &nbsp;at Promise._settlePromiseFromHandler (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:517:31)<br> &nbsp; &nbsp;at Promise._settlePromise (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:574:18)<br> &nbsp; &nbsp;at Promise._settlePromise0 (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:619:10)<br> &nbsp; &nbsp;at Promise._settlePromises (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:699:18)<br> &nbsp; &nbsp;at Promise._fulfill (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:643:18)<br> &nbsp; &nbsp;at PromiseArray._resolve (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise_array.js:126:19)<br> &nbsp; &nbsp;at PromiseArray._promiseFulfilled (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise_array.js:144:14)<br> &nbsp; &nbsp;at Promise._settlePromise (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:579:26)<br> &nbsp; &nbsp;at Promise._settlePromise0 (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:619:10)<br> &nbsp; &nbsp;at Promise._settlePromises (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/promise.js:699:18)<br> &nbsp; &nbsp;at _drainQueueStep (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/async.js:138:12)<br> &nbsp; &nbsp;at _drainQueue (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/async.js:131:9)<br> &nbsp; &nbsp;at Async._drainQueues (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/async.js:147:5)<br> &nbsp; &nbsp;at Immediate.Async.drainQueues [as _onImmediate] (/home/rafael/codaisseur/week6/wednesday/backend/node_modules/bluebird/js/release/async.js:17:14)<br> &nbsp; &nbsp;at processImmediate (internal/timers.js:439:21)
```

**Comment by davidystephenson** [comment]
I think I know the solution, you need to first create the associated entity (looking at your error, I think the User), and then pass it's ID to sequelize. Otherwise, sequelize does not know what user to relate to. You may want to just create the user automatically in your route handler, since for this project, each product has its own user.
